version: '3'

services:
  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
