/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: discord-bot/src/proto/server/users.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export class UserFilter extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        id?: string;
    }): UserFilter {
        const message = new UserFilter({});
        if (data.id != null) {
            message.id = data.id;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserFilter {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserFilter();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): UserFilter {
        return UserFilter.deserialize(bytes);
    }
}
export class BooleanReturn extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        result?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("result" in data && data.result != undefined) {
                this.result = data.result;
            }
        }
    }
    get result() {
        return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
    }
    set result(value: boolean) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        result?: boolean;
    }): BooleanReturn {
        const message = new BooleanReturn({});
        if (data.result != null) {
            message.result = data.result;
        }
        return message;
    }
    toObject() {
        const data: {
            result?: boolean;
        } = {};
        if (this.result != null) {
            data.result = this.result;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.result != false)
            writer.writeBool(1, this.result);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BooleanReturn {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BooleanReturn();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.result = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): BooleanReturn {
        return BooleanReturn.deserialize(bytes);
    }
}
interface GrpcUnaryServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
}
interface GrpcStreamServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
}
interface GrpWritableServiceInterface<P, R> {
    (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
}
interface GrpcChunkServiceInterface<P, R> {
    (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
}
interface GrpcPromiseServiceInterface<P, R> {
    (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
    (message: P, options?: grpc_1.CallOptions): Promise<R>;
}
export abstract class UnimplementedUsersService {
    static definition = {
        isVolunteer: {
            path: "/Users/isVolunteer",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: UserFilter) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => UserFilter.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: BooleanReturn) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => BooleanReturn.deserialize(new Uint8Array(bytes))
        },
        isEditor: {
            path: "/Users/isEditor",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: UserFilter) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => UserFilter.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: BooleanReturn) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => BooleanReturn.deserialize(new Uint8Array(bytes))
        },
        isAdmin: {
            path: "/Users/isAdmin",
            requestStream: false,
            responseStream: false,
            requestSerialize: (message: UserFilter) => Buffer.from(message.serialize()),
            requestDeserialize: (bytes: Buffer) => UserFilter.deserialize(new Uint8Array(bytes)),
            responseSerialize: (message: BooleanReturn) => Buffer.from(message.serialize()),
            responseDeserialize: (bytes: Buffer) => BooleanReturn.deserialize(new Uint8Array(bytes))
        }
    };
    [method: string]: grpc_1.UntypedHandleCall;
    abstract isVolunteer(call: grpc_1.ServerUnaryCall<UserFilter, BooleanReturn>, callback: grpc_1.sendUnaryData<BooleanReturn>): void;
    abstract isEditor(call: grpc_1.ServerUnaryCall<UserFilter, BooleanReturn>, callback: grpc_1.sendUnaryData<BooleanReturn>): void;
    abstract isAdmin(call: grpc_1.ServerUnaryCall<UserFilter, BooleanReturn>, callback: grpc_1.sendUnaryData<BooleanReturn>): void;
}
export class UsersClient extends grpc_1.makeGenericClientConstructor(UnimplementedUsersService.definition, "Users", {}) {
    constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
        super(address, credentials, options);
    }
    isVolunteer: GrpcPromiseServiceInterface<UserFilter, BooleanReturn> = (message: UserFilter, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<BooleanReturn> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.isVolunteer(message, metadata, options, (error: grpc_1.ServiceError, response: BooleanReturn) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    isEditor: GrpcPromiseServiceInterface<UserFilter, BooleanReturn> = (message: UserFilter, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<BooleanReturn> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.isEditor(message, metadata, options, (error: grpc_1.ServiceError, response: BooleanReturn) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
    isAdmin: GrpcPromiseServiceInterface<UserFilter, BooleanReturn> = (message: UserFilter, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): Promise<BooleanReturn> => { if (!metadata) {
        metadata = new grpc_1.Metadata;
    } if (!options) {
        options = {};
    } return new Promise((resolve, reject) => super.isAdmin(message, metadata, options, (error: grpc_1.ServiceError, response: BooleanReturn) => {
        if (error) {
            reject(error);
        }
        else {
            resolve(response);
        }
    })); };
}
